services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www             # Mount project root inside container
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - smartduuka_network

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - smartduuka_network

  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - vendor_data:/app/vendor
      - node_modules:/app/node_modules
      - storage_data:/app/storage
      - media_data:/app/public/media
    healthcheck:
      test: [ "CMD-SHELL", "php-fpm-healthcheck || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - smartduuka_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: redis
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "sleep 2 && redis-cli -a ${REDIS_PASSWORD} ping | grep PONG" ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - smartduuka_network

volumes:
  postgres_data:
  redis_data:
  vendor_data:
  node_modules:
  storage_data:
  media_data:

networks:
  smartduuka_network:
    external: true
